apiVersion: v1
kind: Service
metadata:
  name: go-web-app
spec:
  selector:
    app.kubernetes.io/name: go-web-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9376
  type: ClusterIP